# include_recipe "custom_php_ini"
# include_recipe "jenkins_on_util"
#include_recipe "fix_maintenance_nginx"
# include_recipe "mongodb"
#include_recipe "fluentd"
# include_recipe "own_newrelic"
include_recipe "goodname_newrelic"
